import * as graphqlYoga from 'graphql-yoga'
import * as nodeFs from 'node:fs/promises';
import * as nodeHttp from 'node:http'
 
async function main() {
  const yoga = graphqlYoga.createYoga({
    schema: graphqlYoga.createSchema({
      typeDefs: await getSchema(),
    }),
  })

  const server = nodeHttp.createServer(yoga)

  server.listen(4000, () => {
    console.info('Server is running on http://localhost:4000/graphql')
  })
}

async function getSchema(): Promise<string> {
	// Generated by //src/schema:bundle and required as a data dependency.
	const buffer = await nodeFs.readFile(`src/schema/bundle.graphql`);
  return buffer.toString()
}
 
main()
