load("@rules_graphql_npm//:graphql-buddy/package_json.bzl", graphql_buddy_bin = "bin")

package(default_visibility = ["//visibility:public"])

graphql_buddy_bin.graphql_buddy_binary(
    name = "graphql-buddy",
)
