name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  tests:
    uses: bazel-contrib/.github/.github/workflows/bazel.yaml@v7.2.3
    with:
      folders: |
        [".", "docs", "e2e/bzlmod"]
      exclude: |
        [{"bzlmodEnabled": false}]

  # For branch protection settings, this job provides a "stable" name that can
  # be used to gate PR merges on "all matrix jobs were successful".
  conclusion:
    needs:
      - tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5
      - name: report success
        if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0
      - name: report failure
        if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
